destination_frame: main_lidar_link
scan_destination_topic: /scan_main
laserscan_topics: /scan_front_filtered /scan_rear_filtered
angle_min: -3.1415927410125732
angle_max: 3.1415927410125732
angle_increment: 0.00683698570355773
scan_time: 0.0
range_min: 0.10
range_max: 40.0